print("*******LOVE Calculator*********")
print("")
print("Enter Your Name=")
your_name=input()
print("Enter Your Partner  Name=")
partner_name=input()

p=your_name.count("l")
P=your_name.count("L")
q=your_name.count("o")
Q=your_name.count("O")
r=your_name.count("v")
R=your_name.count("V")
s=your_name.count("e")
S=your_name.count("E")
t=your_name.count("t")
T=your_name.count("T")
u=your_name.count("r")
U=your_name.count("R")
v=your_name.count("u")
V=your_name.count("U")
w=your_name.count("e")
W=your_name.count("E")
name1=p+q+r+s+t+u+v+w+P+Q+R+S+T+U+V+W

a=partner_name.count("l")
A=partner_name.count("L")
b=partner_name.count("o")
B=partner_name.count("O")
c=partner_name.count("v")
C=partner_name.count("V")
d=partner_name.count("e")
D=partner_name.count("E")
e=partner_name.count("t")
E=partner_name.count("T")
f=partner_name.count("r")
F=partner_name.count("R")
g=partner_name.count("u")
G=partner_name.count("U")
h=partner_name.count("e")
H=partner_name.count("E")
name2=a+b+c+d+e+f+g+h+A+B+C+D+E+F+G+H


print("Your love is {}{}%".format(name1,name2))

